#-- See main makefile at ../common/common.mk

#-- Project configuration ------------------------------------------------------

# Project name as used in generated code.
PROJ_NAME = 	diagnostic

#-- HW configuration. Will be passed on to TB as generics/parameters -----------
# (None of that here.)

# Include the main makefile body with all the rules.
include ../common/common.mk
