#-- See main makefile at ../common/common.mk

#-- Project configuration ------------------------------------------------------

# SW build parameters.
PROJ_NAME = hello

# HW configuration. Will be passed on to TB as generics/parameters.
# (None of that here.)

# Include the main makefile body with all the rules.
include ../common/common.mk
